# site settings
title: Stacks # title should be short, like the company name. It is added to the page title tag
name: Stacks # name is for sharing meta data; it should be the name for the "overall site"
description: Site description should be between 130-155 characters
logo: /img/company-logo.png
share_logo: /img/share-company-logo.png # Social media posting. FB (Size should be at min 600 x 315. Better size is 1200 x 630) Twitter (min size 280px x 150px)
baseurl: / # the subpath of your site, e.g. /blog/
site_author: Stacks


# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.hfstacks.com


# build settings
markdown: kramdown
highlighter: pygments # or rouge or null

kramdown:
  auto_ids: false

# paginate
paginate: 10
paginate_path: articles/page:num


# pretty urls - see Jekyll docs for alternatives.
permalink: articles/:title


# exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, node_modules, gulpfile.js, package.json, bower.json]


# Social networking links used in footer. Update and remove as you like.
facebook:           //www.facebook.com
twitter:            //twitter.com
google_plus:        //plus.google.com
linkedin:           //www.linkedin.com


# Analytics and webmaster tools stuff goes here
# Google elements were put in with upload & code in footer
google_analytics:
google_verify:


# default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      author: Stacks
      layout: post
      class: article
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page


# sass
sass:
  style: :compressed


# compress html
compress_html:
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]